services:
  libreria-app:
    build:
      context: .                # tu proyecto actual
      dockerfile: Dockerfile   # Dockerfile dentro de tu proyecto local
    container_name: libreria-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:file:/data/libreria_db
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      EXTERNAL_API_BOOKS_URL: https://my-json-server.typicode.com/Gabriel-Arriola-UTN/libros/books
    ports:
      - "8080:8080"
    volumes:
      - h2_data:/data
    restart: unless-stopped

volumes:
  h2_data:
